### ISSUE TITLE
Regarding implementation of code in python

### ISSUE THREAD

**Issue by kumarballapavan** [weitingchen83/Dehazing-PMHLD-Patch-Map-Based-Hybrid-Learning-DehazeNet-for-Single-Image-Haze-Removal-TIP-2020#1]
I have tried for 2 weeks to implement code, but I couldnt. I do not have NVIDIA graphic card and its drivers. For the code, the latest packages are not working and also the older version of packages are not available. I am really fed up with this! Can we implement the entire algorithm in matlab without any packages support.

**Comment by kumarballapavan** [comment]
Finally I have installed CUDA, CUDNN and also implemented some of the projects. But in this project I face the issue as mentioned below:

TypeError: ('Keyword argument not understood:', 'data_format')

Full Description:

C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
import end
import end
Read img from: ./testImg
Len of the file: 2
[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 100.0% ...Loading data...
(0,) data shape
----------Build Model----------
import end
Build 10
(480, 640, 3) shape
WARNING:tensorflow:From C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2022-05-14 18:09:01.757747: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\activations.py:115: UserWarning: Do not pass a layer instance (such as bound_relu) as the activation argument of another layer. Instead, advanced activation layers should be used just like any other layer in a model.
  identifier=identifier.__class__.__name__))
WARNING:tensorflow:From C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\backend\tensorflow_backend.py:3138: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "./predict.py", line 109, in <module>
    modelRecoverCombine = model.build_combine_model()
  File "D:\Study\NIT Research\Dehazing Matlab Codes\python\2020\J PMHLD\PMHLD\model\model.py", line 157, in build_combine_model
    modelA = load_model('./modelParam/A.h5')
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\engine\topology.py", line 2514, in from_config
    process_layer(layer_data)
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\engine\topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\utils\generic_utils.py", line 146, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\engine\topology.py", line 1271, in from_config
    return cls(**config)
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\layers\core.py", line 483, in __init__
    super(Flatten, self).__init__(**kwargs)
  File "C:\Users\MY DELL\anaconda3\envs\cuda_pytorch\lib\site-packages\keras\engine\topology.py", line 293, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'data_format')
